import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';

// Copyright 2022 Vercel, Inc.
export default function Home() {
  return (
    <>
      <Head>
        <title>Magayaga Labs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Magayaga Labs is new research and development technology
          </p>
          <div>
            <a
              href="cjmagayaga.pages.dev"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <b>Cyril John Magayaga</b>
            </a>
          </div>
        </div>

        <div className={styles.center}>
        <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
          <div>
          <Image
            className={styles.logo}
            src="/vercel.svg"
            alt="Next.js Logo"
            width={200}
            height={30}
            priority
          />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="#"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={styles.headingtwo}>
              Open-source projects <span>→</span>
            </h2>
            <p className={styles.headingone}>
            We encourage you to browse through our featured projects to find work to use, share, and build on!
            </p>
          </a>

          <a
            href="#"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={styles.headingtwo}>
              Products and Services <span>→</span>
            </h2>
            <p className={styles.headingone}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="#"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={styles.headingtwo}>
              Documentations <span>→</span>
            </h2>
            <p className={styles.headingone}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="#"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={styles.headingtwo}>
              Learn <span>→</span>
            </h2>
            <p className={styles.headingone}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}